### ISSUE TITLE
printLn: ambient authority via FFI?

### ISSUE THREAD

**Issue by dckc** [austral/austral#336]
In the section on [capability-based security](https://austral-lang.org/tutorial/capability-based-security), I'm happy to see:

> Capabilities cannot be acquired out of thin air: they must be passed by the client.

but in [hello world](https://austral-lang.org/tutorial/hello-world), the capability to print seems to come from thin air:

```
        printLn("Hello, world!");
```

I don't see it in the [pervasive module spec](https://austral-lang.org/spec/spec.html#austral.pervasive).

but I found it in the implementation:

https://github.com/austral/austral/blob/de2c8ff8c7064ace1cb24fdfa9060bdfffbcbb1f/lib/BuiltIn.ml#L55

A debug-trace facility is often a practical expedient in capability-based systems, but it's typically defined in such a way that programs can't rely on it for their functionality. The capability to write to stdout -- especially unfiltered -- is typically an explicit capability.

**Comment by eudoxia0** [comment]
The reason for this is social rather than technical. Obviously the right thing to do is to have a `Terminal` capability (perhaps broken down into `TerminalRead` and `TerminalWrite`).

The problem with this is the hello world example then becomes extremely convoluted. Most people expect to be able to print to the screen without much ceremony. They might be put off by the fact that it has a whole lot of "bureaucracy" just to write a string to the terminal.

Long-term however yes this is a big problem.

**Comment by dckc** [comment]
> The problem with this is the hello world example then becomes extremely convoluted.

Is there more to it than adding the `root` arg to `main` and changing `printLn` to `root.printLn`?

That is: can you arrange for `TerminalWrite.printLn` to be available on `root`?

Perhaps there's some stuff around linear types that I'm not considering...

**Comment by eudoxia0** [comment]
Done right, it would be like this:

```
module body HelloWorld is
    function main(root: RootCapability): ExitCode is
        let termcap: TerminalCapability := acquireTermCap(&!root);
        printLn(&termcap, "Hello, world!");
        surrenderTermCap(termcap);
        surrenderRoot(root);
        return ExitSuccess();
    end;
end module body.
```

**Comment by dckc** [comment]
Since, as you say,  people expect to be able to print to the screen without much ceremony, can you add a `printLn` method to the `RootCapability`? That is, could it look like this?

```
module body HelloWorld is
    function main(root: RootCapability): ExitCode is
        printLn(&root, "Hello, world!");
        surrenderRoot(root);
        return ExitSuccess();
    end;
end module body.
```

These 3 lines would get moved down to the `printLn` method of `RootCapability`:

```
        let termcap: TerminalCapability := acquireTermCap(&!root);
        printLn(&termcap, "Hello, world!");
        surrenderTermCap(termcap);
```

**Comment by eudoxia0** [comment]
The problem here is one of passing too much power.

If a function takes the `RootCapability` it can do _anything_. You would expect standard library code to use it appropriately, and not maliciously, but it could still go wrong. The point is that functions should be passed the narrowest possible capabilities.

**Comment by ckp95** [comment]
Might be the first step along the complexity road to hell, but:

Maybe the solution could be to have an escape-hatch `debugPrint` function that needs no capability to run. But it only does anything if you provide a `--debug` compiler flag. It would be used for debugging only and would not be used for real software. Without the debug flag, it's a no-op. That way, you don't end up in the situation where you have a misbehaving function 50 layers down the callstack, and suddenly you need to alter 50 nested function signatures to pass in a TerminalWrite capability, just to debug it.

But for functions where writing to the terminal is actually something that should be externally visible (user-facing terminal output, logging, etc), you do it the "hard way" and pass the capabilities in.

Risks of this:

- devs get lazy and release debug builds to users
- race conditions due to timing differences in the `--debug` vs non-debug builds
- complexity spirit demon smile

**Comment by eudoxia0** [comment]
I've been thinking about this on and off and I think you might be right. Maybe have a build mode that can be either `debug` or `release`, and in the `debug` mode there's an implicitly imported module called `Austral.Debug` that has the `Printable` typeclass with the methods implemented, and you can call `debugPrint` and `debugPrintLn`.

Meanwhile there should be a different typeclass for printing in the stdlib that would use actual capability security.

**Comment by eudoxia0** [comment]
Moved this to a discussion here: #392
