### ISSUE TITLE
Implicit conversion from a numeric type to Int32 when an arithmetic operation is involved

### ISSUE THREAD

**Issue by kenaryn** [austral/austral#432]
This is a my very first issue posted in my life so I hope I mess not around:

Could be related to <a href="https://github.com/austral/austral/issues/433">#433</a>.

Defining a natural number works as expected, *e.g.*:
`let n: Nat8 := 11;` compiles successfully.

But when one tries to perform an arithmetic operation at the right hand side of the expression, an implicit conversion to `Int32` occurs, *e.g.*:
`let n: Nat8 := 11 * 4`;

Hence, the compiler complains about:
`Expected a value of type 'Nat8', but got a value of type 'Int32'.`

Whereas the expected behaviour shall be that the program compiles without any raised error.

EDIT: The same malfunctionning seems to occur with all numeric types except `Int32`, *e.g.*:
`let age: Int8 := 37 + 1`;
returns the same aforementioned error.

**Comment by eudoxia0** [comment]
Hmm. So, the "lenient" type checking only works for integer literals, and not for _expressions_ involving integer literals. Integer literals have a type of `Int32`, so the type of an expression involving integer literals is `Int32`.

The fix for this would involve adding a constant-folding step where expressions like `11*4` and `37+1` are evaluated to `44` and `38` respectively. Then the existing type-matching infra would work.

Alternatively (and I'd rather not do this) the type checker could be extended to handle a specific type for integer literals (I'd very much rather not do this).

The ergonomics here is bad, so I will fix this.
