### ISSUE TITLE
Implicit conversion from a numeric type to Int32 with generic records

### ISSUE THREAD

**Issue by kenaryn** [austral/austral#433]
Could be related to <a href="https://github.com/austral/austral/issues/432">#432</a>.

Constructing a record with generic types holding a type parameter set as numeric type other than `Int32` fails to compile with the following error:
`Expected a value of type 'Nat16', but got a value of type 'Int32'.`

Here is a minimal reproducible offending snippet:

```
record Biography[A: Type, B: Type]: Type is
   first: A;
   second: B;
end;

let aurele: Biography[FixedArray[Nat8], Nat16] := Biography(first => "Aurele", second => 38);
```

**Comment by eudoxia0** [comment]
Does this work?

```
let aurele: Biography[FixedArray[Nat8], Nat16] := Biography(first => "Aurele", second => (38 : Nat16));
```

I feel like type casting should have better syntax. The colon is kind of easily missed.

**Comment by kenaryn** [comment]
Yes, thank you, it works indeed. And the type casting syntax is fine by me.

On a side note, it seems like the type casting is able to resolve a statement but not an expression (or am I wrong?), *i.e.* `(...) second => (38: Nat16)` works but (...) `second => ((30 + 8): Nat16)` works and returns a `Bad conversion` error.

**Comment by eudoxia0** [comment]
Yeah so the main problem here is "lenient" type checking of integer literals works in limited places. Basically if you have `let x: Nat16 := 10` then it works. And if you have `x + 10` you don't need to cast `10` to whatever type `x` is for it to work.

Adding lenient type checking to more sophisticated places is harder. For example, if you have a typeclass with a method `foo(x)`, and that class is implemented over many integer types, it's not clear how it should work. Like does `foo(3)` pick the instance for `Int32` or `Nat16` or which one?

Records are hard too because they may be generic.

If you have:

```austral
record Foo: Free is
    x: Nat8;
end;
```

Then `Foo(x => 30)` is perfectly constrained, and the compiler could easily guess what it is, but what if the type of `x` is generic? As you get more complicated, you need increasingly complex type inference to figure out just what an integer type is.

I think I could add lenient type checking for some record/union constructors, but you shouldn't expect it to work everywhere, or with full generality.

**Comment by eudoxia0** [comment]
>I think I could add lenient type checking for some record/union constructors, but you shouldn't expect it to work everywhere, or with full generality.

Oh actually this is already implemented for concrete record types. Test here: `test-programs/suites/003-record/005-integer-literals`

Anyways I think I'm closing this as WONTFIX because doing this for generic records requires too much type inference work.
